server:
  port: 8080

spring:
  application:
    name: secure-customer-identity-api

  datasource:
    url: jdbc:h2:mem:identitydb
    driver-class-name: org.h2.Driver
    username: sa
    password:

  h2:
    console:
      enabled: true

  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://dev-g8roucgnp64r37t0.us.auth0.com/
          audiences: https://secure-customer-identity-api

management:
  endpoints:
    web:
      exposure:
        include: health,info

  endpoint:
    health:
      probes:
        enabled: true
      show-details: always
